# Generated by Django 3.1.3 on 2020-12-29 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDb',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 28, 19, 21, 44, 809406))),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
